[package]
name = "filewatch-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
notify = "6.1.1"
rusqlite = { version = "0.32.1", features = ["bundled"] }
minus = { version = "5.5.0", features = ["dynamic_output"] }
clap = { version = "4.4", features = ["derive"] }
log = "0.4"
simplelog = "0.12"